# Generated by Django 5.1.1 on 2024-10-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_usercustomer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usercustomer',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
