# Generated by Django 4.2.16 on 2024-10-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usercustomer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomer',
            name='img',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
    ]
