# Generated by Django 5.1.1 on 2024-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercustomer_password_usercustomer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
