# Generated by Django 4.2.16 on 2024-10-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_usercustomer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomer',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
