# Generated by Django 5.1.1 on 2024-11-17 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_alter_usercustomer_password_alter_usercustomer_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='active', max_length=10)),
                ('required_details', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='UserPayments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('payment_details', models.JSONField(default=dict)),
                ('status', models.CharField(default='active', max_length=10)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usercustomer')),
            ],
        ),
    ]
