# Generated by Django 4.2.16 on 2024-10-08 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_Method',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('payment_Details', models.TextField(max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('payment_Method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.payment_method')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.usercustomer')),
            ],
        ),
    ]
