# Generated by Django 5.1.1 on 2024-11-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productdetails_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
