# Generated by Django 5.1.1 on 2024-11-17 10:53

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('status', models.CharField(default='toProgress', max_length=10)),
                ('total', models.FloatField(default=0)),
                ('prepaid', models.FloatField(default=0)),
                ('remaining', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
